In [4]:
import pandas as pd

s = pd.Series([85, 90, 88])
print(s)

0    85
1    90
2    88
dtype: int64

In [5]:
s.index=[20,30,40]
print(s)

20    85
30    90
40    88
dtype: int64

In [6]:
 marks = pd.Series([78, 85, 62, 90, 74])

In [15]:
numbers_s=pd.Series([10,20,30,40],index=["a","b","c","d"])

numbers_s.iloc[3]
numbers_s.loc["b"]

np.int64(20)

In [31]:
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
"Age": [20, 21, 19, 18],
"Marks":[95,85,64,72]}
methu=pd.DataFrame(data)
methu.loc[0:2]

    Name  Age  Marks
0    Tom   20     95
1   nick   21     85
2  krish   19     64

In [34]:
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
"Age": [20, 21, 19, 18],
"Marks":[95,85,64,72]}

methu=pd.DataFrame(data)
methu.loc[1,1]

KeyError: 1

In [40]:
methu.index = ['A', 'B', 'C', 'D']
(methu)

    Name  Age  Marks
A    Tom   20     95
B   nick   21     85
C  krish   19     64
D   jack   18     72

In [42]:
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
"Age": [20, 21, 19, 18],
"Marks":[95,85,64,72]
}
Students=pd.DataFrame(data)
Students

    Name  Age  Marks
0    Tom   20     95
1   nick   21     85
2  krish   19     64
3   jack   18     72

In [46]:
import pandas as pd

data = {
    "BC": [65, 73, 82, 45, 93, 56],
    "DDI": [96, 88, 52, 77, 69, 48],
    "AM": [55, 43, 66, 80, 90, 78],
    "SMA": [45, 63, 56, 71, 92, 81],
    "AF": [68, 73, 46, 30, 85, 93],
    "BISC": [77, 81, 93, 74, 51, 42]
}

Marks = pd.DataFrame(data)
print(Marks)

   BC  DDI  AM  SMA  AF  BISC
0  65   96  55   45  68    77
1  73   88  43   63  73    81
2  82   52  66   56  46    93
3  45   77  80   71  30    74
4  93   69  90   92  85    51
5  56   48  78   81  93    42

In [47]:
Marks.columns

Index(['BC', 'DDI', 'AM', 'SMA', 'AF', 'BISC'], dtype='object')

In [55]:
Marks.iloc[0:7]

   BC  DDI  AM  SMA  AF  BISC
0  65   96  55   45  68    77
1  73   88  43   63  73    81
2  82   52  66   56  46    93
3  45   77  80   71  30    74
4  93   69  90   92  85    51
5  56   48  78   81  93    42

In [56]:
Marks.values

array([[65, 96, 55, 45, 68, 77],
       [73, 88, 43, 63, 73, 81],
       [82, 52, 66, 56, 46, 93],
       [45, 77, 80, 71, 30, 74],
       [93, 69, 90, 92, 85, 51],
       [56, 48, 78, 81, 93, 42]])

In [57]:
Marks["DDI"]

0    96
1    88
2    52
3    77
4    69
5    48
Name: DDI, dtype: int64

In [58]:
Marks.iloc[2]

BC      82
DDI     52
AM      66
SMA     56
AF      46
BISC    93
Name: 2, dtype: int64

In [59]:
Marks.loc[:, "AM":"AF"]

   AM  SMA  AF
0  55   45  68
1  43   63  73
2  66   56  46
3  80   71  30
4  90   92  85
5  78   81  93

In [60]:
Marks[Marks["BC"] > 60]

   BC  DDI  AM  SMA  AF  BISC
0  65   96  55   45  68    77
1  73   88  43   63  73    81
2  82   52  66   56  46    93
4  93   69  90   92  85    51

In [ ]:
Marks[(Marks["BC"] > 60) & (Marks["BISC"] < 55)]